apiVersion: skaffold/v2beta1
kind: Config
metadata:
  name: spring-on-kubernetes
build:
  artifacts:
  - image: docker.io/vw98008/spring-on-kubernetes
    jib:
      project: com.example:spring-on-kubernetes
deploy:
  kubectl:
    manifests:
    - k8s/deployment.yaml
    - k8s/service.yaml
